### ISSUE TITLE
Signing does not work on web-deployed PKC instances

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/mediawiki-extensions-Aqua#317]
![image](https://user-images.githubusercontent.com/45313235/150113702-67b3d5f4-51da-49be-8c15-214dbb6d8c6f.png)

Signing does not work anymore on web-public instances of PKC's. I tested on different pages, it does not have to do with the content of the page.

**Comment by FantasticoFox** [comment]
[exception] [7af77ddc2744b0286178458e] /rest.php/data_accounting/write/store_signed_tx   TypeError: Argument 1 passed to DataAccounting\Util\TransclusionHashExtractor::__construct() must be of the type string, null given, called in /var/www/html/extensions/DataAccounting/includes/Hook/AddTransclusionHashesOnSave.php on line 101
#0 /var/www/html/extensions/DataAccounting/includes/Hook/AddTransclusionHashesOnSave.php(101): DataAccounting\Util\TransclusionHashExtractor->__construct(NULL, Title, ParserOutput, TitleFactory, DataAccounting\Verification\VerificationEngine, ParserFactory)
#1 /var/www/html/includes/HookContainer/HookContainer.php(160): DataAccounting\Hook\AddTransclusionHashesOnSave->onMultiContentSave(MediaWiki\Revision\RenderedRevision, User, CommentStoreComment, integer, Status)
#2 /var/www/html/includes/HookContainer/HookRunner.php(2595): MediaWiki\HookContainer\HookContainer->run(string, array)
#3 /var/www/html/includes/Storage/PageUpdater.php(795): MediaWiki\HookContainer\HookRunner->onMultiContentSave(MediaWiki\Revision\RenderedRevision, User, CommentStoreComment, integer, Status)
#4 /var/www/html/extensions/DataAccounting/includes/Override/Storage/DAPageUpdater.php(67): MediaWiki\Storage\PageUpdater->saveRevision(CommentStoreComment, integer)
#5 /var/www/html/extensions/DataAccounting/includes/Verification/VerificationEngine.php(195): DataAccounting\Override\Storage\DAPageUpdater->saveRevision(CommentStoreComment, integer)
#6 /var/www/html/extensions/DataAccounting/includes/Verification/VerificationEngine.php(127): DataAccounting\Verification\VerificationEngine->storeSignature(DataAccounting\Verification\Entity\VerificationEntity, User, string)
#7 /var/www/html/extensions/DataAccounting/includes/API/WriteStoreSignedTxHandler.php(78): DataAccounting\Verification\VerificationEngine->signRevision(MediaWiki\Revision\RevisionStoreRecord, User, string, string, string)
#8 /var/www/html/includes/Rest/SimpleHandler.php(38): DataAccounting\API\WriteStoreSignedTxHandler->run()
#9 /var/www/html/includes/Rest/Router.php(403): MediaWiki\Rest\SimpleHandler->execute()
#10 /var/www/html/includes/Rest/Router.php(330): MediaWiki\Rest\Router->executeHandler(DataAccounting\API\WriteStoreSignedTxHandler)
#11 /var/www/html/includes/Rest/EntryPoint.php(165): MediaWiki\Rest\Router->execute(MediaWiki\Rest\RequestFromGlobals)
#12 /var/www/html/includes/Rest/EntryPoint.php(130): MediaWiki\Rest\EntryPoint->execute()
#13 /var/www/html/rest.php(31): MediaWiki\Rest\EntryPoint::main()
#14 {main}

**Comment by FantasticoFox** [comment]
The other error which I'm not sure if it's related is this this:

[DBQuery] LCStoreDB::get [0.001s] database: SELECT  lc_value  FROM `l10n_cache`    WHERE lc_lang = 'en' AND lc_key = 'messages:tweeki-sidebar-left'  LIMIT 1  
[DBConnection] Wikimedia\Rdbms\LoadBalancer::getLocalConnection: reused a connection for local/0
[DBQuery] LCStoreDB::get [0s] database: SELECT  lc_value  FROM `l10n_cache`    WHERE lc_lang = 'en' AND lc_key = 'messages:tweeki-container-class'  LIMIT 1  
[GlobalTitleFail] MessageCache::parse called with no title set.
#0 /var/www/html/includes/language/Message.php(1333): MessageCache->parse(string, NULL, boolean, boolean, LanguageEn)
#1 /var/www/html/includes/language/Message.php(930): Message->parseText(string)
#2 /var/www/html/includes/language/Message.php(961): Message->format(string)
#3 [internal function]: Message->__toString()
#4 /var/www/html/skins/Tweeki/includes/TweekiTemplate.php(142): stripos(Message, string)
#5 /var/www/html/skins/Tweeki/includes/TweekiTemplate.php(85): TweekiTemplate::renderPage(TweekiTemplate)
#6 /var/www/html/includes/skins/SkinTemplate.php(129): TweekiTemplate->execute()
#7 /var/www/html/includes/skins/SkinTemplate.php(144): SkinTemplate->generateHTML()
#8 /var/www/html/includes/OutputPage.php(2644): SkinTemplate->outputPage()
#9 /var/www/html/includes/exception/MWExceptionRenderer.php(158): OutputPage->output()
#10 /var/www/html/includes/exception/MWExceptionRenderer.php(77): MWExceptionRenderer::reportHTML(TypeError)
#11 /var/www/html/includes/exception/MWExceptionHandler.php(107): MWExceptionRenderer::output(TypeError, integer)
#12 /var/www/html/includes/exception/MWExceptionHandler.php(202): MWExceptionHandler::report(TypeError)
#13 /var/www/html/includes/exception/MWExceptionHandler.php(170): MWExceptionHandler::handleException(TypeError, string)
#14 [internal function]: MWExceptionHandler::handleUncaughtException(TypeError)
#15 {main}

**Comment by FantasticoFox** [comment]
Fixed in a732845c3f9651b6d62df38d7702443d0216cf45
